//
//  SuccessErrorModel.swift
//  Shanab
//
//  Created by Macbook on 4/29/20.
//  Copyright © 2020 Dtag. All rights reserved.
//

import Foundation
import Foundation
class SuccessError_Model {
    var successMessage: String = ""
    var errorMessage = ""
    var name = [String]()
    var user_id = [Int]()
    var email = [String]()
    var role = [String]()
    var password = [String]()
    var password_confirmation = [String]()
    var reset_password_code = [String]()
    var old_password = [String]()
    var new_password = [String]()
    var new_password_confirmation = [String]()
    var image = [String]()
    var username = [String]()
    var phone = [String]()
    var product_id = [String]()
    var quantity = [String]()
    var id = [String]()
    var order_id = [String]()
    var rate = [String]()
    var review = [String]()
    var type = [String]()
    var keyword = [String]()
    var value = [String]()
    var city_id = [String]()
    var Address = [String]()
    var longitude = [String]()
    var latitude = [String]()
    var category_id = [String]()
    var address = [String]()
    var code = [String]()
    var date = [String]()
    var coupon = [String]()
    var visit_fees = [String]()
    var agent_id = [String]()
    var payment_method = [String]()
    var time = [String]()
    var device_token = [String]()
    var status = [String]()
    var cancel_reason = [String]()
    var account = [String]()
    var agent_description = [String]()
    var birthday = [String]()
    var national_id2 = [String]()
    var cost = [String]()
    var comment = [String]()
    var token = [String]()
    var description = [String]()
    var restaurant_id = [String]()
    var number_of_persons = [String]()
    var item_id = [String]()
    var item_type = [String]()
    var un_active_account = String()
    var currency = [String]()
    var message = [String]()
    var total = [String]()
    var cartItems = [String]()
    var floor = [String]()
    var country_id = [String]()
    var area_id = [String]()
    var building = [String]()
    var apartment = [String]()
    var meal_id = [String]()
    var options = [String]()
    var condition = [String]()
    var ducoments = [String]()
}
